#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# This prompt is a standalone: it doesn't require any secondary files.
# Just 'source <filename>' and you have your new prompt.  Because it's a
# standalone, the git detail is very limited (only whether or not you're in
# a git folder, not whether/how much it's modified.)
#
# It was also designed to have a particularly distinctive marker, as a
# reminder that you're running as root.

# shellcheck disable=SC1090  # "Can't follow non-constant source."
# shellcheck disable=SC2154  # "referenced but not assigned"

# set the following to "true" or "false" to display ephemeral data after
# the prompt:
wantsEphemera="true"
# load points (percentage) at which the load caret indicator appears, and
# then changes colour:
MEDIUMLOAD=50
HIGHLOAD=100

echo "Prompt Title: basicroot - prompt with colour block, intended as stand-alone prompt for root"
echo "Includes:     user@host:dir, git (basic), newline, battery, return value, ephemeral: CPU count, load, du"
#, load indicator"
echo "For:          a dark background (should work with light)"
echo "Requires:     git, Powerline font (looks okay without?)"

export bgred='\[\033[41m\]'
export bgyellow='\[\033[43m\]'
export black='\[\033[0;30m\]'
export red='\001\033[31m\002'
export bg_gray='\001\033[47m\002'
export darkgray='\033[38;5;008m'
export nocolour='\001\033[0;0m\002'

if ( command uname -a | command grep Darwin > /dev/null )
then
    export _p_os="Darwin"
elif ( command uname -a | command grep Linux > /dev/null )
then
    export _p_os="Linux"
else
    export _p_os="?"
fi

_p_loadcaret () {
    load="$(command uptime | command awk '{print $(NF-2)}' | command tr -d ",")"
    percentload="$(command echo -e "scale=0 ; ${load}*100/${_p_numthreads}" | command bc)"
    if (( percentload > HIGHLOAD ))
    then
        _p_loadcaret_color="${bgred}"
    elif (( percentload > MEDIUMLOAD ))
    then
        _p_loadcaret_color="${bgyellow}"
    else
        _p_loadcaret_color=""
    fi

    if [ -n "${_p_loadcaret_color}" ]
    then
        echo -e "${_p_loadcaret_color}^${_pc_nocolour}"
    fi
}

_p_threadcount() {
    # shellcheck disable=SC2154  # "referenced but not assigned"
    if [ "${_p_os}" == "Linux" ]
    then
        numCPUs="$(grep -c 'siblings' /proc/cpuinfo)"
    elif [ "${_p_os}" == "Darwin" ]
    then
        # this method valid Monterey / 2022-02
        numCPUs="$(sysctl -n hw.ncpu)"
    else
        numCPUs="?"
    fi
    echo -n "${numCPUs}"
}

_p_df_percent() {
    # shellcheck disable=SC2154  # "referenced but not assigned"
    if [ "${_p_os}" == "Linux" ]
    then
        # finds all local mount-points and shows their percent use in parens
        while read -r mountpoint
        do
            echo -n "($( df --output=pcent "${mountpoint}" | tail -n +2 | tr -d " " ))"
        done < <(command lsblk --output MOUNTPOINT --noheadings | command grep -v '^$' | command grep -v '[SWAP]' | command grep -v '^/snap/' )
    elif [ "${_p_os}" == "Darwin" ]
    then
        echo -n "?"
    else
        echo -n "?"
    fi
}

_p_load() {
    command uptime | command awk '{print $(NF-2)}' | command tr -d ","
}

case ${TERM} in
    xterm*|rxvt*)
        # the first "\u@\h" is the Icon Title
        # the second "\u@\h:\w" is goes into the XTerm Title Bar
        # shellcheck disable=SC1117 #  Backslash is literal in ...
        export _p_TITLEBAR="\[\033]1;\u@\h\007\033]2;\u@\h:\w\007\]"
        if [ "$(command uname -a | command grep Darwin > /dev/null ; echo $?)" == "0" ]
        then
            # Macs don't understand the "Icon Title":
            # shellcheck disable=SC1117 #  Backslash is literal in ...
            export _p_TITLEBAR="\[\033]0;\u@\h:\w\007\]"
        fi
        ;;
    *)
        export _p_TITLEBAR=""
        ;;
esac

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

# line 1

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${bgred}  ${nocolour}${red}${nocolour}"
# shellcheck disable=SC1117 #  Backslash is literal in ...
PS1+="\u@\h:\w"
PS1+="${green}\$(if command git status >/dev/null 2>&1; then echo '(git)'; fi)"
PS1+="${green}\$(if command svn info   >/dev/null 2>&1; then echo '(svn)'; fi)"

# line 2

PS1+="\n"
PS1+="${bgred} ${black}${bgred}${nocolour} "
num_batteries=$(command ls -1d /sys/class/power_supply/BAT* 2>/dev/null | command wc -l)
if (( num_batteries > 0 ))
then
    PS1+="\$(cat /sys/class/power_supply/BAT?/capacity)% "
fi
PS1+="${bg_gray}${red}\${_p_retval}${nocolour}"
if ! "${wantsEphemera}"
then
    PS1+="\$(_p_loadcaret)"
fi
PS1+="\\\$ "

# EPHEMERAL - borrowed from hl-hostname2

PS1+="\$(
    if \$wantsEphemera
    then
        tput sc
        echo -en \"        ${darkgray}[\$(_p_threadcount)] \$(_p_load) \$(_p_df_percent)\"
        tput rc
    fi
)"

