#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# This prompt is a standalone: it doesn't require any secondary files.
# Just 'source <filename>' and you have your new prompt.  Because it's a
# standalone, the git detail is very limited (only whether or not you're in
# a git folder, not whether/how much it's modified.)  TODO: add a load
# indicator.
#
# It was also designed to have a particularly distinctive marker, as a
# reminder that you're running as root.

# shellcheck disable=SC1090  # "Can't follow non-constant source."
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: basicroot - relatively simple prompt with colour block, intended as stand-alone prompt for root"
echo "Includes:     user@host:dir, git (basic), newline, battery, return value"
#, load indicator"
echo "For:          a dark background (should work with light)"
echo "Requires:     git"

export bgred='\[\033[41m\]'
export black='\[\033[0;30m\]'
export red='\001\033[31m\002'
export bg_gray='\001\033[47m\002'
export nocolour='\001\033[0;0m\002'

case ${TERM} in
    xterm*|rxvt*)
        # the first "\u@\h" is the Icon Title
        # the second "\u@\h:\w" is goes into the XTerm Title Bar
        # shellcheck disable=SC1117 #  Backslash is literal in ...
        export _p_TITLEBAR="\[\033]1;\u@\h\007\033]2;\u@\h:\w\007\]"
        if [ "$(command uname -a | command grep Darwin > /dev/null ; echo $?)" == "0" ]
        then
            # Macs don't understand the "Icon Title":
            # shellcheck disable=SC1117 #  Backslash is literal in ...
            export _p_TITLEBAR="\[\033]0;\u@\h:\w\007\]"
        fi
        ;;
    *)
        export _p_TITLEBAR=""
        ;;
esac

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

# line 1

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${bgred}  ${nocolour}${red}${nocolour}"
# shellcheck disable=SC1117 #  Backslash is literal in ...
PS1+="\u@\h:\w"
PS1+="${green}\$(if command git status >/dev/null 2>&1; then echo '(git)'; fi)"
PS1+="${green}\$(if command svn info   >/dev/null 2>&1; then echo '(svn)'; fi)"

# line 2

PS1+="\n"
PS1+="${bgred} ${black}${bgred}${nocolour} "
num_batteries=$(command ls -1d /sys/class/power_supply/BAT* 2>/dev/null | command wc -l)
if (( num_batteries > 0 ))
then
    PS1+="\$(cat /sys/class/power_supply/BAT?/capacity)% "
fi
PS1+="${bg_gray}${red}\${_p_retval}${nocolour}"
PS1+="\\\$ "

