#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype

# shellcheck disable=SC1090  # "Can't follow non-constant source."
# shellcheck disable=SC1091  # "<file> was not specified as input"
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: blupnk256_2 - blue-pink-256-colours (take 2)"
echo "Includes:     user@host, dir, git, newline, screen/tmux indicator, battery, return value, load indicator"
echo "For:          a dark background"
echo "Requires:     git, 256 colour terminal"
source "${PROMPTDIR}/session/_p_256warning"
_p_256warning

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_loadcaret"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"

# 021 057 093 129 165 201

_p_pink="\[\033[038;5;201m\]"
_p_blue="\[\033[038;5;021m\]"
if (( UID == 0 ))
then
    _p_usercolour="${_pc_b_red}"
else
    _p_usercolour="${_p_pink}"
fi

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    _p_retval=$? # capture the return value before you change it w/prompt
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

# add the titlebar:
PS1="${_p_TITLEBAR}"
# add user @ hostname:
PS1+="${_p_usercolour}\u"
PS1+="${_p_blue}@"
PS1+="${_p_pink}\h "
# add the blue-pink gradient:
# 021 057 093 129 165 201
PS1+="\[\033[48;5;021m\] \[\033[48;5;057m\] \[\033[48;5;093m\] \[\033[48;5;129m\] \[\033[48;5;165m\] \[\033[48;5;201m\] \[\033[0m\]"
# add the current directory:
PS1+="\[\033[48;5;201m\]${_p_blue}\$(_p_tildepwd)${_pc_nocolour}"
PS1+="\[\033[38;5;201m\]${_pc_nocolour}"
# if the current directory isn't writeable, tag it:
PS1+="\$(if ! [ -w \"\${PWD}\" ]; then echo \"[ro]\"; fi)"
# add git branch and status:
PS1+=" ${_p_pink}\$(_p_git)"
# second line:
PS1+="\n"
PS1+="${_p_pink}"
# add indicators if in tmux or screen:
if ${_p_in_tmux}
then
    PS1+="[t]"
fi
if ${_p_in_screen}
then
    PS1+="[s]"
fi
# add battery indicator (if we have one):
if ${_p_has_battery}
then
    PS1+="\$(_p_powerconnected)\$(_p_powerpercent)% "
fi
PS1+="${_pc_nocolour}"
PS1+="\$(_p_loadcaret)"
# add the return value of the previous command if non-zero:
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"
PS1+="${_p_blue}\\\$ ${_pc_nocolour}"

