#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: cyan-purple-2-bgd"
echo "Includes:     battery, PWD, git status, newline, user@host"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

# directory is coloured differently if it's not writable
# user is red if root, otherwise fits colour scheme

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

# set the user colour based on privileges:
# this only needs to be run once per session, so not a part of
# prompt_command.
if (( UID == 0 ))
then
    # Colour indicator when you're logged in as root:
    export _p_usercolour=${_pc_b_red}
else
    export _p_usercolour=${_pc_b_purple}
fi

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    # set the directory colour based on access:
    if [ -w "${PWD}" ]
    then
        _p_dircolour="$(echo -e "${_pc_b_purple}")"
        export _p_dircolour
    else
        _p_dircolour="$(echo -e "${_pc_b_purple}${_pc_bg_gray}")"
        export _p_dircolour
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${_pc_b_cyan}["
PS1+="${_pc_purple}\$(_p_powerconnected)${_pc_b_purple}\$(_p_powerpercent)%"
PS1+="${_pc_b_cyan}]["
PS1+="\${_p_dircolour}\$(_p_tildepwd)"
PS1+="${_pc_nocolour}${_pc_b_cyan}]"
PS1+="${_pc_nocolour} \$(_p_git)"
PS1+="\n"                                                # newline
# _p_usercolour is only needed once per session (ie. not escaped):
PS1+="${_p_usercolour}\u${_pc_b_cyan}@${_pc_b_purple}\h"
PS1+="${_pc_b_gray}\$${_pc_nocolour} "

export PS1

