#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: datetimegit"
echo "Includes:     date, colourslash pwd, git, uptime, user@host"
echo "For:          a dark background"
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_colourslashpwd"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/time/_p_yyyy-mm-dd"
# This one is usually called by _p_uptime, but we need it separately
# to test uptime in PROMPT_COMMAND:
source "${PROMPTDIR}/machine/_p_upseconds"
source "${PROMPTDIR}/machine/_p_uptime"

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi

    # minimum days of uptime before uptime is shown:
    local minuptime=5
    if (( $(_p_upseconds) >= ( minuptime * 24 * 60 * 60 ) ))
    then
        _p_up="$(_p_uptime)"
    else
        _p_up=""
    fi

    if command git status >/dev/null 2>&1
    then
        # set some variables to be displayed later
        _p_displayGit="($(_p_git))"
    else
        _p_displayGit=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}\$(_p_yyyy-mm-dd)" # date in yyyy-mm-dd format
PS1="${PS1}:"           # add a colon
PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour} )" # add PWD with off-colour slashes
PS1="${PS1}${_pc_b_green}\${_p_displayGit}" # add git status in green
PS1="${PS1}${_pc_nocolour}"          # colours off
PS1="${PS1}\n"                       # newline
PS1="${PS1}${_pc_b_red}"             # bright red
PS1="${PS1}\${_p_up}"                # uptime (if greater than some value)
PS1="${PS1}${_pc_nocolour}"          # colours off
PS1="${PS1}:"                        # colon
PS1="${PS1}\u@\h"                    # user @ hostname
PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}" # return value
PS1="${PS1}${_pc_b_yellow}"          # bright yellow
PS1="${PS1}\$"                       # $ or # depending on user
PS1="${PS1}${_pc_nocolour} "

export PS1

