#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# A clone of my MacBook Pro prompt.

# set the following to "true" or "false" to display ephemeral data after
# the prompt:
wantsEphemera="false"

echo "Prompt Title: gomacbp"
echo "Includes:     git status, PWD, newline, battery, user@host, ephemeral load"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git_branch_only"
source "${PROMPTDIR}/directory/_p_git_status_only"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_threadcount"
source "${PROMPTDIR}/machine/_p_load3"

if [ "${_p_uid0}" == "true" ]
then
    export _p_usercolour="${_pc_b_red}"
else
    export _p_usercolour="${_pc_b_gray}"
fi

#This isn't going to change, let's set it once:
threadcount="$(_p_threadcount)"

prompt_command () {
    _p_retval=$? # capture the return value before you change it w/prompt
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
    _p_xtermtitle # generates the _p_TITLEBAR variable

    # Fill after_text with the number of CPUs and the load
    after_text="[${threadcount}]$(_p_load3)"
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
if [ "${_p_in_tmux}" == "true" ]
then
    PS1+="[t]"
fi
if [ "${_p_in_screen}" == "true" ]
then
    PS1+="[s]"
fi
PS1+="${_p_TITLEBAR}"
PS1+="${_pc_b_gray}-${_pc_b_blue}-("
PS1+="\$(if ! [ -w \"\${PWD}\" ]; then echo \"${_pc_bg_red}\"; fi)"
PS1+="${_pc_b_yellow}\$(_p_tildepwd)"
PS1+=" ${_pc_b_purple}\$(_p_git_branch_only)"
PS1+="${_pc_purple}\$(_p_git_status_only)"
PS1+="${_pc_nocolour}${_pc_b_blue})-${_pc_b_gray}-"
# Newline
PS1+="${_pc_nocolour}\n"
PS1+="${_pc_b_gray}-${_pc_b_blue}-("
PS1+="${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1+="${_pc_nocolour} "
# User @ Hostname:
PS1+="${_p_usercolour}\u${_pc_b_blue}@${_pc_b_gray}\h"
PS1+="${_pc_b_blue})-${_pc_b_gray}-"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"
PS1+="${_pc_b_gray}\$"
PS1+="${_pc_nocolour} "

# EPHEMERAL -

if $wantsEphemera
then
PS1+="\[\$(
    tput sc
    echo -en \"          ${_c_darkgray}\${after_text}${_c_nocolour}\"
    tput rc
)\]"
fi

export PS1

