#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Named for its dominant colour.  No git support.

echo "Prompt Title: greeny"
echo "Includes:     user@host, history, PWD, newline, time (no git)"
echo "For:          a dark background (colours don't work well on Mac)"
echo "Requires:     "

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/machine/_p_shorttty"
source "${PROMPTDIR}/machine/_p_df_sl"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_tildepwd"

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
if [ "${_p_in_tmux}" == "true" ]
then
    PS1+="[t]"
fi
if [ "${_p_in_screen}" == "true" ]
then
    PS1+="[s]"
fi
PS1+="${_pc_b_black}-${_pc_green}-${_pc_b_green}("
# User @ Hostname:
PS1+="${_pc_nocolour}${_pc_green}\u${_pc_b_black}@${_pc_nocolour}${_pc_green}\h"
PS1+="${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_green}("
PS1+="${_pc_nocolour}${_pc_green}\!"
PS1+="${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_green}("
PS1+="${_pc_b_gray}\$(_p_shorttty)"
PS1+="${_pc_b_black}:"
PS1+="${_pc_nocolour}${_pc_green}\$(_p_tildepwd)"
PS1+=" ${_pc_italics}\$(_p_git)${_pc_nocolour}"
PS1+="${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
PS1+="\n" # ------------------------------------------
PS1+="${_pc_b_black}-${_pc_green}-${_pc_b_green}("
PS1+="${_pc_b_green}\D{%H%M}"
PS1+="${_pc_nocolour}${_pc_green}:"
PS1+="${_pc_b_gray}\\\$"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"
PS1+="${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
PS1+="${_pc_nocolour} "
PS1+="\[\$(
    tput sc
    echo -en \"   ${_c_darkgray}\$(_p_df_sl)  \$(date +%m-%d-%H%M)${_c_nocolour}\"
    tput rc
)\]"

export PS1

