#!/bin/bash # helps vim identify the filetype
#
# Named for its dominant colour.  No git support.

pushd "${PROMPTDIR}" > /dev/null

echo "Prompt Title: greeny"
echo "Includes:     user@host, history, tty, PWD, newline, time"
echo "For:          a dark background (colours don't work well on Mac)"
echo "Requires:     "

# Get the components we need:
source _p_colours # get colours into the environment
source machine/_p_shorttty
source directory/_p_xtermtitle
source directory/_p_tildepwd
popd > /dev/null

_p_xtermtitle # generates the _p_TITLEBAR variable

export PROMPT_COMMAND="" # blank this if you're not using it

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_b_black}-${_pc_green}-${_pc_b_green}("
# User @ Hostname:
PS1="${PS1}${_pc_nocolour}${_pc_green}\u${_pc_b_black}@${_pc_nocolour}${_pc_green}\h"
PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_green}("
PS1="${PS1}${_pc_nocolour}${_pc_green}\!"
PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_green}("
PS1="${PS1}${_pc_b_gray}\$(_p_shorttty)"
PS1="${PS1}${_pc_b_black}:"
PS1="${PS1}${_pc_nocolour}${_pc_green}\$(_p_tildepwd)"
PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
PS1="${PS1}\n" # ------------------------------------------
PS1="${PS1}${_pc_b_black}-${_pc_green}-${_pc_b_green}("
PS1="${PS1}${_pc_b_green}\D{%H%M}"
PS1="${PS1}${_pc_nocolour}${_pc_green}:"
PS1="${PS1}${_pc_b_gray}\$"
PS1="${PS1}${_pc_b_green})${_pc_nocolour}${_pc_green}-${_pc_b_black}"
PS1="${PS1}${_pc_nocolour} "

export PS1

