#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Named for its bright colours.

echo "Prompt Title: hl-hostname2"
echo "Includes:     battery-dir-git, newline, user@host, retval, ephemeral load and df"
echo "For:          a dark background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_df_sl"
source "${PROMPTDIR}/machine/_p_df_percent"
source "${PROMPTDIR}/machine/_p_threadcount"
source "${PROMPTDIR}/machine/_p_load1"

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    # set some variables to be displayed later
    _p_displayGit="$(_p_git)"
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

_p_xtermtitle # generates the _p_TITLEBAR variable

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

# What colour should the highlighted host value be:
HOSTCOLOUR="${_pc_bg_blue}${_pc_b_green}"

# -----------------------------------------------------------------------------

PS1="${_pc_nocolour}${_p_TITLEBAR}"

# BATTERY

# shellcheck disable=SC2089  # Quotes/backslashes will be treated literally
if [[ "${_p_has_battery}" == "true" ]]
then
    PS1+="${_pc_b_gray}$(_p_powerconnected)$(_p_powerpercent)% "
fi

# DIRECTORY

PS1+="${_pc_b_yellow}\$(_p_tildepwd)"

# GIT

# shellcheck disable=SC2089  # Quotes/backslashes will be treated literally
PS1+="\$(
if [ \"\${_p_displayGit}x\" != \"x\" ]
then
    echo -en \" ${_pc_green}\$(_p_git)\"
fi
)"

# NEWLINE

PS1+="\n"

# USER-HOST

PS1+="${_pc_nocolour}\u@"
PS1+="${HOSTCOLOUR}\h${_pc_nocolour}"

# RETURN VALUE

PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"

# HASH OR DOLLAR PROMPT

PS1+=" ${_pc_b_yellow}\\\$"
PS1+="${_pc_nocolour} "

# EPHEMERAL -

PS1+="\[\$(
    tput sc
    echo -en \"        ${_c_darkgray}[\$(_p_threadcount)] \$(_p_load1) \$(_p_df_percent)\"
    tput rc
)\]"

# shellcheck disable=SC2090  # Quotes/backslashes in this variable will not
# be respected.
export PS1

