#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Named for its bright colours.

echo "Prompt Title: hl-hostname"
echo "Includes:     user@host, PWD, newline, (if exists) battery, git"
echo "For:          a dark background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    # set some variables to be displayed later
    _p_displayGit="$(_p_git)"
    if [[ "${_p_has_battery}" == "true" ]]
    then
        _p_displayPower="$(_p_powerconnected)$(_p_powerpercent)%"
    else
        _p_displayPower=""
    fi
    _p_tilde="~"
    # on Linux/Bash4 we need "\~", on Mac/Bash3 we need "~" in this
    # substitution, so we get around it by making it a variable ...:
    _p_dir="${PWD/${HOME}/${_p_tilde}}"
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

HOSTCOLOUR="${_pc_bg_blue}${_pc_b_green}"

PS1="${_pc_nocolour}\u@"
PS1="${PS1}${HOSTCOLOUR}\h${_pc_nocolour}"
PS1="${PS1}${_pc_yellow}:"
PS1="${PS1}${_pc_b_yellow}\$(_p_tildepwd)"
PS1="${PS1}\n" # ------------------------------------------
PS1="${PS1}\$(  # battery
if [ \"\${_p_displayPower}x\" != \"x\" ]
then
    echo -en \"${_pc_b_gray}\${_p_displayPower} \"
fi
)"
PS1="${PS1}\$(  # git
if [ \"\${_p_displayGit}x\" != \"x\" ]
then
    echo -en \"${_pc_b_yellow}(${_pc_green}\$(_p_git)${_pc_b_yellow})\"
fi
)"
PS1="${PS1}${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}${_pc_b_yellow}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

