#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
# shellcheck disable=SC1090  # Can't follow non-constant source.
# shellcheck disable=SC1091  # Not following: <pathname> not specified as input
# shellcheck disable=SC2154  # VAR is referenced but not assigned.
# shellcheck disable=SC2034  # $VAR appears unused (for extra colours)

echo "Prompt Title: 'lblue,' light blue"
echo "Includes:     battery, dir w/git, newline, user@host, retval, $/#"
echo "For:          a dark background"
echo "Requires:     git, 256 colour terminal, TrueType font"
source "${PROMPTDIR}/session/_p_256warning"
_p_256warning

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git_branch_only"
source "${PROMPTDIR}/directory/_p_git_status_only"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/session/_p_inother" # provides $_p_parentenv variable
source "${PROMPTDIR}/directory/_p_xtermtitle"

_p_blue1="\[\033[038;5;021m\]"
_p_blue2="\[\033[038;5;027m\]"
_p_blue3="\[\033[038;5;033m\]"
_p_blue4="\[\033[038;5;039m\]"
_p_blue5="\[\033[038;5;045m\]"
_p_blue6="\[\033[038;5;051m\]"
_p_nocolour="\[\033[0m\]"

prompt_command () {
    _p_retval=$? # capture the return value before you change it w/prompt
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
# add the terminal titlebar:
PS1+="${_p_TITLEBAR}"
# add a colour bar on the far right:
PS1+="\$(
tput sc
tput cuf \$(( \${COLUMNS} - 7 ))
echo -en '\[\033[048;5;021m\] \[\033[048;5;027m\] \[\033[048;5;033m\] \[\033[048;5;039m\] \[\033[048;5;045m\] \[\033[048;5;051m\] \[\033[0m\]'
tput rc
)"
# battery display if we have it:
if ${_p_has_battery}
then
    PS1+="${_p_blue4}\$(_p_powerconnected)\$(_p_powerpercent)%${_p_nocolour} "
fi
if [ -n "${_p_parentenv}" ]
then
    PS1+="${_p_blue2}${_p_parentenv}${_p_nocolour} "
fi
PS1+="${_p_blue6}\${PWD//\${HOME}/\~} "
PS1+="${_p_blue5}\$(_p_git_branch_only)${_p_nocolour}"
PS1+="${_p_blue3}\$(_p_git_status_only)${_p_nocolour}"

PS1+="\n"   ################################# NEWLINE

# add battery indicator (if we have one):
PS1+="${_p_blue5}\u${_p_blue2}@${_p_blue5}\h${_p_nocolour}" # user@host
# add the return value of the previous command if non-zero:
PS1+="\$(
if [ -n \"\${_p_retval}\" ]
then
    echo \"\[\033[048;5;021m\]${_pc_b_red}\${_p_retval}${_p_nocolour}\"
fi
)"
PS1+="${_p_blue1}\\\$${_p_nocolour} "

