#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Single line with cropped PWD (based on one-long-trad)
# for a light background.

echo "Prompt Title: one-short-bgl"
echo "Includes:     battery, user@hostname, short PWD, git status"
echo "For:          a light background" # Mac? works on Linux
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_shortpwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

export PROMPT_COMMAND="" # blank this if you're not using it

PS1="${_pc_nocolour}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1="${PS1}${_p_nocolour} "
PS1="${PS1}${_pc_black}\u${_pc_b_blue}@${_pc_black}\h"
PS1="${PS1}${_p_nocolour}:"
PS1="${PS1}${_pc_nocolour}\$(_p_shortpwd 15)"
PS1="${PS1}${_pc_black}\$(_p_git)"
PS1="${PS1}${_pc_blue}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

