#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Source this file to use the prompt immediately.
#
# Single line, fairly traditional but long prompt.

echo "Prompt Title: one-long-trad"
echo "Includes:     battery, user@host, PWD, git status"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
    if command git status >/dev/null 2>&1
    then
        # we're in a git repo:
        git_out="($(_p_git))"
    else
        git_out=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${_pc_nocolour}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1+="${_p_nocolour} "
PS1+="${_pc_b_green}\u@\h"
PS1+="${_p_nocolour}:"
PS1+="${_pc_b_blue}\$(_p_tildepwd)"
PS1+="${_pc_nocolour}\${git_out}"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="\$ "

export PS1

