#!/bin/bash # helps vim identify the filetype
#
# Single line with cropped PWD (based on one-long-trad)

pushd "${PROMPTDIR}" > /dev/null

echo "Prompt Title: one-short"
echo "Includes:     battery, user@host, PWD, git status"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

# Get the components we need:
source _p_colours # get colours into the environment
source directory/_p_xtermtitle
source directory/_p_git
source directory/_p_shortpwd
source machine/_p_powerconnected
source machine/_p_powerpercent
popd > /dev/null

function prompt_command () {
    _p_xtermtitle # generates the _p_TITLEBAR variable
    local tmp=$(_p_git)
    if [ "${tmp}x" == "x" ]
    then
        _p_git_output=""
    else
        _p_git_output="-${tmp}"
    fi
}

export PROMPT_COMMAND=prompt_command

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_nocolour}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1="${PS1}${_p_nocolour} "
PS1="${PS1}${_pc_b_gray}\u${_pc_b_black}@${_pc_b_gray}\h"
PS1="${PS1}${_p_nocolour}:"
PS1="${PS1}${_pc_nocolour}\$(_p_shortpwd 15)"
PS1="${PS1}${_pc_b_gray}\${_p_git_output}"
PS1="${PS1}${_pc_b_yellow}\$${_pc_nocolour} "

export PS1

