#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Single line with cropped PWD (based on one-long-trad)

echo "Prompt Title: one-short"
echo "Includes:     battery, user@host, PWD, git status"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_shortpwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_df_stoplight"

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi

    _p_xtermtitle # generates the _p_TITLEBAR variable
    local tmp
    tmp=$(_p_git)
    if [ "${tmp}x" == "x" ]
    then
        _p_git_output=""
    else
        _p_git_output="◆${tmp}"
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
if ${_p_has_battery}
then
    PS1+="${_pc_nocolour}\$(_p_powerconnected)\$(_p_powerpercent)%"
    PS1+="${_p_nocolour} "
fi
PS1+="\$(_p_df_stoplight)"
PS1+="${_pc_b_gray}\u${_pc_b_black}@${_pc_b_gray}\h"
PS1+="${_p_nocolour}:"
PS1+="${_pc_nocolour}\$(_p_shortpwd 15)"
PS1+="${_pc_nocolour}\${_p_git_output}"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="${_pc_b_yellow}\$${_pc_nocolour} "

export PS1

