#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# A one- or two-line prompt.  The number of lines varies according to how
# much content is in the prompt.  Adjust "minRemainingWidth" variable to
# change the behaviour.  Same as "onetwopower" prompt but doesn't do width
# fill - which significantly reduces the complexity and no longer requires
# the maintainenance of two different versions.

echo "Prompt Title: onetwopowernofill"
echo "Includes:     pwd, git, power, user@host"
echo "For:          a dark background"
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
export PROMPT_COMMAND="" # blank this if you're not using it

minRemainingWidth=50

prompt_command () {
    # set some variables to be displayed later
    p_displayGit="$(_p_git)"
    p_displayPower="($(_p_powerconnected)$(_p_powerpercent)%)"
    _p_tilde="~"
    # on Linux/Bash4 we need "\~", on Mac/Bash3 we need "~" in this
    # substitution, so we get around it by making it a variable ...:
    _p_dir="${PWD/${HOME}/${_p_tilde}}"
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=prompt_command

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}\$(
remainingWidth=\$(( COLUMNS - \${#p_displayPower} - \${#_p_dir} - \${#p_displayGit} - \$(echo "\u@\h" | wc -c) - 3 ))

echo -en \"${_pc_b_gray}\${p_displayPower}${_pc_nocolour}\"
echo -en \"\${_p_dir}\"
if [ \"\${p_displayGit}x\" != \"x\" ]
then
    echo -en \"${_pc_b_gray}|\"
    echo -en \"${_pc_b_green}\${p_displayGit}\"
fi

if (( remainingWidth <= minRemainingWidth )) ; # the two line version
then
    echo -en \"\n\"
else   # the one line version
    echo -en \"${_pc_b_gray}|\"
fi
echo -en \"${_pc_nocolour}\u${_pc_b_yellow}@${_pc_nocolour}\h\"
echo -e  \"${_pc_b_yellow}\$${_pc_nocolour} \";
)"

export PS1

