#!/bin/bash
#
# A one- or two-line prompt.  The number of lines varies according to how
# much content is in the prompt.  Adjust "minRemainingWidth" variable to
# change the behaviour.

pushd ${PROMPTDIR} > /dev/null

echo "Prompt Title: onetwo"
echo "Includes:     pwd, git, user@host"
echo "For:          a dark background"
echo "Requires:     git"

source _p_colours # get colours into the environment
source directory/_p_git
source directory/_p_xtermtitle
export PROMPT_COMMAND="" # blank this if you're not using it
popd > /dev/null

minRemainingWidth=50

prompt_command () {
    p_displayGit="$(_p_git)"
    p_dir="${PWD/${HOME}/\~}"
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=prompt_command

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}\$(
remainingWidth=\$(( COLUMNS - \${#p_dir} - \${#p_displayGit} - \$(echo "\u@\h" | wc -c) - 3 ))

if [ \${remainingWidth} -le ${minRemainingWidth} ] ;
then
    fillWidth=\$(( COLUMNS - \${#p_dir} - \${#p_displayGit} ))
    fill=\"\";
    for (( i=0 ; i<\${fillWidth} ; i=i+1))
    do
        fill=\"\${fill} \"
    done

    echo -en \"\${p_dir}\"
    echo -en \"\${fill}\"
    echo -en \"${_pc_b_green}\${p_displayGit}${_pc_nocolour}\"
    echo -en \"\n\"
    echo -en \"\u${_pc_b_yellow}@${_pc_nocolour}\h\"
    echo -e  \"${_pc_b_yellow}\$${_pc_nocolour} \";
else
    echo -en \"\${p_dir}\"
    if [ \"\${p_displayGit}x\" != \"x\" ]
    then
        echo -en \"${_pc_b_gray}|\"
        echo -en \"${_pc_b_green}\${p_displayGit}\"
    fi
    echo -en \"${_pc_b_gray}|\"
    echo -en \"${_pc_nocolour}\u${_pc_b_yellow}@${_pc_nocolour}\h\"
    echo -e  \"${_pc_b_yellow}\$${_pc_nocolour} \";
fi
)"

export PS1

