#!/bin/bash
#
# A one- or two-line prompt.  The number of lines varies according to how
# much content is in the prompt.  Adjust "minRemainingWidth" variable to
# change the behaviour.  Same as "onetwo" prompt but adds power indicator.
# Same as "onetwopower" but ... more purple.

pushd "${PROMPTDIR}" > /dev/null

echo "Prompt Title: onetwopowerpurple"
echo "Includes:     pwd, git, power, user@host"
echo "For:          a dark background"
echo "Requires:     git"

source _p_colours # get colours into the environment
source directory/_p_git
source directory/_p_xtermtitle
source machine/_p_powerconnected
source machine/_p_powerpercent
export PROMPT_COMMAND="" # blank this if you're not using it
popd > /dev/null

minRemainingWidth=50

prompt_command () {
    # set some variables to be displayed later
    p_displayGit="$(_p_git)"
    p_displayPower="($(_p_powerconnected)$(_p_powerpercent)%)"
    _p_tilde="~"
    # on Linux/Bash4 we need "\~", on Mac/Bash3 we need "~" in this
    # substitution, so we get around it by making it a variable ...:
    _p_dir="${PWD/${HOME}/${_p_tilde}}"
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=prompt_command

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}\$(
remainingWidth=\$(( COLUMNS - \${#p_displayPower} - \${#_p_dir} - \${#p_displayGit} - \$(echo "\u@\h" | wc -c) - 3 ))

if [ \${remainingWidth} -le ${minRemainingWidth} ] ; # the two line version
then
    fillWidth=\$(( COLUMNS - \${#p_displayPower} - \${#_p_dir} - \${#p_displayGit} ))
    fill=\"\";
    for (( i=0 ; i<\${fillWidth} ; i=i+1))
    do
        fill=\"\${fill} \"
    done

    echo -en \"${_pc_b_purple}\${p_displayPower}${_pc_nocolour}\"
    echo -en \"${_pc_purple}\${_p_dir}${_pc_nocolour}\"
    echo -en \"\${fill}\"
    echo -en \"${_pc_b_gray}\${p_displayGit}${_pc_nocolour}\"
    echo -en \"\n\"
    echo -en \"${_pc_b_yellow}\u${_pc_b_purple}@${_pc_b_yellow}\h\"
    echo -e  \"${_pc_b_purple}\$${_pc_nocolour} \";
else   # the one line version
    echo -en \"${_pc_b_purple}\${p_displayPower}${_pc_nocolour}\"
    echo -en \"${_pc_purple}\${_p_dir}${_pc_nocolour}\"
    if [ \"\${p_displayGit}x\" != \"x\" ]
    then
        echo -en \"${_pc_b_purple}|\"
        echo -en \"${_pc_b_gray}\${p_displayGit}\"
    fi
    echo -en \"${_pc_b_purple}|\"
    echo -en \"${_pc_b_yellow}\u${_pc_b_purple}@${_pc_b_yellow}\h\"
    echo -e  \"${_pc_b_purple}\$${_pc_nocolour} \";
fi
)"

export PS1

