#!/bin/bash # helps vim identify the filetype
#
# This one has everything.
#
# It's probably quite resource-hungry and a bad idea on things like
# Raspberry Pis.
#
# 2018-05-05: stat fails (missing operand) in a directory where there are
# no real files - ie. /dev/ where it's all devices and links.

pushd "${PROMPTDIR}" > /dev/null

echo "Prompt Title: overload"
echo "Includes:     git, load, file data, colourslash PWD, newline, battery, user@host"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"
echo "Warning:      very processor intensive: switch prompts if it's slow!"

# Get the components we need:
source _p_colours # get colours into the environment
source directory/_p_git
source machine/_p_powerconnected
source machine/_p_powerpercent
source machine/_p_load
source directory/_p_colourslashpwd
source directory/_p_numvisfiles
source directory/_p_numhiddenfiles
source directory/_p_numvisdirs
source directory/_p_numhiddendirs
source directory/_p_numalllinks
source directory/_p_numalldevices
source directory/_p_tildepwd
source directory/_p_statbytesum
source directory/_p_xtermtitle
popd > /dev/null

_p_xtermtitle # generates the _p_TITLEBAR variable
export PROMPT_COMMAND="" # blank this if you're not using it

#####################################################################
#               OS-based Colour Settings                            #
#####################################################################
# Going to have to do Colour Settings for file types by the OS ...
#
# This is a do-once setting, doesn't need to be done for every prompt.
if [ "$(uname -a | grep Darwin > /dev/null ; echo $?)" == "0" ]
then
    # character devices on Mac are blue FG, yellow BG
    # block     devices on Mac are blue FG, cyan   BG
    # Going with "character" as it's more common ...
    # This didn't work:
    #_p_device_colour="${_p_b_blue}${_p_bg_yellow}"
    _p_device_colour="\[\033[43;1;34m\]"
else
    # assuming Linux, more fine-grained control may be needed
    #_p_device_colour="${_p_b_yellow}"
    _p_device_colour="\[\033[1;33m\]"
fi
if [ "$(uname -a | grep Darwin > /dev/null ; echo $?)" == "0" ]
then
    # Didn't work:
    #_p_link_colour="${_p_b_purple}"
    _p_link_colour="\[\033[1;35m\]"
else
    #_p_link_colour="${_p_b_cyan}"
    _p_link_colour="\[\033[1;36m\]"
fi

unset prompt_command

function _p_showobj () {
    # takes two params (whole numbers, no negatives), outputs "x.y":
    #   - initially this was number of visible and hidden files
    #   - x and y value are only echoed if they're non-zero
    #   - the dot is only echoed if there are hidden values
    #   - a trailing space is echoed if either is non-zero
    #
    _p_vis=${1}
    _p_hid=${2}
    if [ ${_p_vis} -gt 0 ]
    then
        echo -n "${_p_vis}"
    fi
    if [ ${_p_hid} -gt 0 ]
    then
        echo -n ".${_p_hid}"
    fi
    if [ $(( _p_vis + _p_hid )) -gt 0 ]
    then
        echo -n " "
    fi
}

PS1="${_p_TITLEBAR}${_pc_b_gray}-"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_b_purple}\$(_p_git)"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_b_gray}-"

#####################################################################
# Load:
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}${_pc_b_yellow}\$(_p_load)"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_b_gray}-"
# Files:
PS1="${PS1}| "
PS1="${PS1}${_pc_b_gray}\$(_p_showobj \$(_p_numvisfiles) \$(_p_numhiddenfiles) )"
PS1="${PS1}${_pc_b_blue}\$(_p_showobj \$(_p_numvisdirs) \$(_p_numhiddendirs) )"
PS1="${PS1}${_p_link_colour}\$(_p_showobj \$(_p_numalllinks) 0 )"
PS1="${PS1}${_p_device_colour}\$(_p_showobj \$(_p_numalldevices) 0 )${_pc_nocolour}"
PS1="${PS1}\$(_p_statbytesum) "
PS1="${PS1}${_pc_b_gray}|"
#####################################################################

PS1="${PS1}-"
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                  # newline
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1="${PS1}${_pc_nocolour} "
PS1="${PS1}${_pc_b_gray}\u"
PS1="${PS1}${_pc_b_blue}@"
PS1="${PS1}${_pc_b_gray}\h"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

