#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # Can't follow non-constant source.
# shellcheck disable=SC2154  # <var> is referenced but not assigned.

cat << EOF
Prompt Title: pointy
Includes:     user@host, dir, git, newline, battery, screen/tmux indicator,
              return value
For:          a dark background
Requires:     git, TTF font
$(tput bold)$(tput setaf 1)WARNING$(tput sgr0):      This prompt requires a TTF font (we can't test
              for font type inside a terminal) and will look bad without it.
EOF

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_loadcaret"
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"

isGit() {
    command git status >/dev/null 2>&1
}

if (( UID == 0 ))
then
    _p_usercolour="${_pc_b_red}"
else
    _p_usercolour=""
fi

COLOUR1="${_pc_b_green}"  # decorations
#COLOUR2="${_pc_b_yellow}" # information
COLOUR2="${_pc_nocolour}" # information

prompt_command () {
    _p_retval=$? # capture the return value before you change it w/prompt
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1="${_p_TITLEBAR}"
PS1+="${COLOUR1}◁ "
PS1+="${COLOUR2}"
PS1+="${_p_usercolour}\u${_pc_nocolour}@\h"
PS1+="${COLOUR1} ○ "
PS1+="${COLOUR2}"
PS1+="\$(_p_tildepwd)"
PS1+="\$(if ! [ -w \"\${PWD}\" ]; then echo \"[ro]\"; fi)"
PS1+="\$(if \$(isGit); then echo \"${COLOUR1}»${COLOUR2}\$(_p_git)\"; fi)"
PS1+="${COLOUR1} ▷"

PS1+="\n"

# add battery indicator (if we have one):
PS1+="${COLOUR2}"
if ${_p_has_battery}
then
    PS1+="\$(_p_powerconnected)\$(_p_powerpercent)%"
fi
if ${_p_in_tmux}
then
    PS1+="[t]"
fi
if ${_p_in_screen}
then
    PS1+="[s]"
fi
PS1+="\$(_p_loadcaret)"
PS1+="${COLOUR1} ○ "
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="${COLOUR1}\\\$${_pc_nocolour} "

