#!/bin/bash # helps vim identify the filetype
#
# Based on "slim" but very purple.

pushd "${PROMPTDIR}" > /dev/null

echo "Prompt Title: purple"
echo "Includes:     PWD, git status (yellow), newline, battery, user@host"
echo "For:          a dark background, bad on Mac" # relies on bold colour difference
echo "Requires:     git"

source _p_colours # get colours into the environment
source machine/_p_powerconnected
source machine/_p_powerpercent
source directory/_p_xtermtitle
source directory/_p_git
source directory/_p_tildepwd

function prompt_command () {
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

export PROMPT_COMMAND=prompt_command
popd > /dev/null

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_purple}"
PS1="${PS1}["
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\$(_p_tildepwd)"
PS1="${PS1}${_pc_purple}"
PS1="${PS1}]"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1} "
PS1="${PS1}${_pc_b_yellow}"
PS1="${PS1}\$(_p_git)"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                           # newline
PS1="${PS1}${_pc_purple}"
PS1="${PS1}["
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\$(_p_powerconnected)"
PS1="${PS1}\$(_p_powerpercent)"
PS1="${PS1}%"
PS1="${PS1}${_pc_purple}"
PS1="${PS1}|"
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\u"
PS1="${PS1}${_pc_purple}"
PS1="${PS1}@"
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\h"
PS1="${PS1}${_pc_purple}"
PS1="${PS1}]"
PS1="${PS1}${_pc_b_gray}"
PS1="${PS1}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

