#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: sa"
echo "Includes:     git status, colour PWD, newline, battery, user@host"
echo "For:          a dark background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_colourslashpwd"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

PS1="${_pc_b_gray}-"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_b_purple}\$(_p_git)"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}-"
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                  # newline
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}${_pc_b_blue}-("
if [ "${_p_has_battery}" == "true" ]
then
    PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
    PS1="${PS1}${_pc_nocolour} "
else
    PS1="${PS1}${_pc_nocolour}"
fi
# User @ Hostname:
PS1="${PS1}${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_b_gray}-"
PS1="${PS1}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

