#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"

echo "Prompt Title: sa-bgl"
echo "Includes:     git status, colour PWD, newline, battery, user@host"
echo "For:          a light background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_colourslashpwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

prompt_command () {
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_black}-"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_b_purple}\$(_p_git)"
PS1="${PS1}${_pc_b_blue}-"
PS1="${PS1}${_pc_black}-"
PS1="${PS1}-"
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_blue} \${_pc_nocolour})"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_black}-"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                  # newline
PS1="${PS1}${_pc_black}-"
PS1="${PS1}${_pc_b_blue}-("
PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1="${PS1}${_pc_nocolour} "
# User @ Hostname:
PS1="${PS1}${_pc_black}\u${_pc_b_blue}@${_pc_black}\h"
PS1="${PS1}${_pc_b_blue})-"
PS1="${PS1}${_pc_black}-"
PS1="${PS1}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

