#!/bin/bash # helps vim identify the filetype
#
# Attempting to re-implement "sa" with linedraw characters

pushd ${PROMPTDIR} > /dev/null
# Get the components we need:
source _p_colours   # get colours into the environment
source _p_linechars # get linedraw characters into the environment
source directory/_p_git
source directory/_p_colourslashpwd
source directory/_p_xtermtitle
source machine/_p_powerconnected
source machine/_p_powerpercent
popd > /dev/null

function prompt_command () {
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

export PROMPT_COMMAND=prompt_command

PS1=""
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_b_gray}${_p_line_tl}"
PS1="${PS1}${_pc_b_blue}${_p_line}"
PS1="${PS1}${_pc_b_purple}\$(_p_git)"
PS1="${PS1}${_pc_b_blue}${_p_line}${_pc_b_gray}${_p_line}"
PS1="${PS1}${_p_line}${_pc_b_blue}${_p_line}("
PS1="${PS1}\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
PS1="${PS1}${_pc_b_blue})${_p_line}"
PS1="${PS1}${_pc_b_gray}${_p_line}"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                  # newline
PS1="${PS1}${_pc_b_gray}${_p_line_ll}"
PS1="${PS1}${_pc_b_blue}${_p_line}("
PS1="${PS1}${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1="${PS1}${_pc_nocolour} "
# User @ Hostname:
PS1="${PS1}${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
PS1="${PS1}${_pc_b_black}\$"
PS1="${PS1}${_pc_b_blue})${_p_line}"
PS1="${PS1}${_pc_b_gray}${_p_line}"
PS1="${PS1}${_pc_nocolour} "

export PS1

