#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Attempting to re-implement "sa" with linedraw characters

echo "Prompt Title: sa2"
echo "Includes:     git status, colour PWD, newline, battery, user@host"
echo "For:          a dark background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours"   # get colours into the environment
source "${PROMPTDIR}/_p_linechars" # get linedraw characters into the environment
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_colourslashpwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/machine/_p_df_sl"

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${_pc_b_gray}${_p_line_tl}"
PS1+="${_pc_b_blue}${_p_line}"
PS1+="${_pc_b_purple}\$(_p_git)"
PS1+="${_pc_b_blue}${_p_line}${_pc_b_gray}${_p_line}"
PS1+="${_p_line}${_pc_b_blue}${_p_line}("
PS1+="\$(_p_colourslashpwd \${_pc_b_red} \${_pc_b_yellow} \${_pc_nocolour})"
PS1+="${_pc_b_blue})${_p_line}"
PS1+="${_pc_b_gray}${_p_line}"
PS1+="${_pc_nocolour}"
PS1+="\n"                  # newline
PS1+="${_pc_b_gray}${_p_line_ll}"
PS1+="${_pc_b_blue}${_p_line}("
PS1+="${_pc_b_purple}\$(_p_powerconnected)\$(_p_powerpercent)%"
PS1+="${_pc_nocolour} "
# User @ Hostname:
PS1+="${_pc_b_gray}\u${_pc_b_blue}@${_pc_b_gray}\h"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="${_pc_b_black}\\\$"
PS1+="${_pc_b_blue})${_p_line}"
PS1+="${_pc_b_gray}${_p_line}"
PS1+="${_pc_nocolour} "
PS1+="\[\$(
    tput sc
    echo -en \"   ${_c_darkgray}\$(_p_df_sl)  \$(date +%m-%d-%H%M)${_c_nocolour}\"
    tput rc
)\]"

export PS1

