#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# The name comes from the hostname it was first used on.

echo "Prompt Title: slim"
echo "Includes:     PWD, git status, newline, battery, user@host"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"

_p_xtermtitle # generates the _p_TITLEBAR variable

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
if [ "${_p_in_tmux}" == "true" ]
then
    PS1+="[t]"
fi
if [ "${_p_in_screen}" == "true" ]
then
    PS1+="[s]"
fi
PS1+="${_p_TITLEBAR}"
PS1+="${_pc_b_cyan}"
PS1+="["
PS1+="${_pc_b_yellow}"
PS1+="\$(_p_tildepwd)"
PS1+="${_pc_b_cyan}"
PS1+="]"
PS1+="${_pc_nocolour}"
PS1+=" "
PS1+="${_pc_b_yellow}"
PS1+="\$(_p_git)"
PS1+="${_pc_nocolour}"
PS1+="\n"                           # newline
PS1+="${_pc_b_cyan}"
PS1+="["
PS1+="${_pc_b_purple}"
PS1+="\$(_p_powerconnected)"
PS1+="\$(_p_powerpercent)"
PS1+="%"
PS1+="${_pc_b_cyan}"
PS1+="]"
PS1+="${_pc_nocolour}"
PS1+=" "
PS1+="${_pc_b_purple}"
PS1+="\u"
PS1+="${_pc_b_cyan}"
PS1+="@"
PS1+="${_pc_b_purple}"
PS1+="\h"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"
PS1+="${_pc_b_gray}"
PS1+="\\\$"
PS1+="${_pc_nocolour} "

export PS1

