#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# The name comes from the hostname it was first used on.

echo "Prompt Title: slim"
echo "Includes:     PWD, git status, newline, battery, user@host"
echo "For:          a dark background" # Mac? works on Linux
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"

function prompt_command () {
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

export PROMPT_COMMAND=prompt_command

PS1=""
if [ "${_p_in_tmux}" == "true" ]
then
    PS1="${PS1}[t]"
fi
if [ "${_p_in_screen}" == "true" ]
then
    PS1="${PS1}[s]"
fi
PS1="${PS1}${_p_TITLEBAR}"
PS1="${PS1}${_pc_b_cyan}"
PS1="${PS1}["
PS1="${PS1}${_pc_b_yellow}"
PS1="${PS1}\$(_p_tildepwd)"
PS1="${PS1}${_pc_b_cyan}"
PS1="${PS1}]"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1} "
PS1="${PS1}${_pc_b_yellow}"
PS1="${PS1}\$(_p_git)"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1}\n"                           # newline
PS1="${PS1}${_pc_b_cyan}"
PS1="${PS1}["
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\$(_p_powerconnected)"
PS1="${PS1}\$(_p_powerpercent)"
PS1="${PS1}%"
PS1="${PS1}${_pc_b_cyan}"
PS1="${PS1}]"
PS1="${PS1}${_pc_nocolour}"
PS1="${PS1} "
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\u"
PS1="${PS1}${_pc_b_cyan}"
PS1="${PS1}@"
PS1="${PS1}${_pc_b_purple}"
PS1="${PS1}\h"
PS1="${PS1}${_pc_b_gray}"
PS1="${PS1}\$"
PS1="${PS1}${_pc_nocolour} "

export PS1

