#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Named for its bright colours.

echo "Prompt Title: tonka"
echo "Includes:     user@host, history #, time, date, newline, PWD"
echo "For:          a dark background"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_tildepwd"
source "${PROMPTDIR}/directory/_p_xtermtitle"

_p_xtermtitle # generates the _p_TITLEBAR variable

PS1="${_pc_b_red}-${_pc_b_blue}-("
# User @ Hostname:
PS1+="${_pc_b_yellow}\u${_pc_b_red}@${_pc_b_yellow}\h"
PS1+="${_pc_b_blue})-("
PS1+="${_pc_b_yellow}\!"
PS1+="${_pc_b_blue})-("
PS1+="${_pc_b_yellow}\D{%H%M}"
PS1+="${_pc_b_red}/"
PS1+="${_pc_b_yellow}\D{%d-%b-%y}"
PS1+="${_pc_b_blue})-${_pc_b_red}-"
PS1+="\n" # ------------------------------------------
PS1+="${_pc_b_red}-${_pc_b_blue}-("
PS1+="${_pc_b_yellow}\$"
PS1+="${_pc_b_red}:"
PS1+="${_pc_b_yellow}\$(_p_tildepwd)"
PS1+="${_pc_b_blue})-${_pc_b_red}-"
PS1+="${_pc_nocolour} "

export PS1

