#!/bin/bash # helps vim identify the filetype
#
# Named for its bright colours.

pushd ${PROMPTDIR} > /dev/null
# Get the components we need:
source _p_colours # get colours into the environment
source directory/_p_xtermtitle
popd > /dev/null

_p_xtermtitle # generates the _p_TITLEBAR variable

export PROMPT_COMMAND="" # blank this if you're not using it

PS1="${_pc_b_yellow}-${_pc_b_blue}-("
# User @ Hostname:
PS1="${PS1}${_pc_b_yellow}\u${_pc_b_blue}@${_pc_b_yellow}\h"
PS1="${PS1}${_pc_b_blue})-("
PS1="${PS1}${_pc_b_yellow}\${PWD}"
PS1="${PS1}${_pc_b_blue})-${_pc_b_yellow}-"
PS1="${PS1}\n" # ------------------------------------------
PS1="${PS1}${_pc_b_yellow}-${_pc_b_blue}-("
PS1="${PS1}${_pc_b_yellow}\D{%H%M}"
PS1="${PS1}${_pc_b_blue}:"
PS1="${PS1}${_pc_b_yellow}\D{%a, %d %b %y}"
PS1="${PS1}${_pc_b_blue}:"
PS1="${PS1}${_pc_b_gray}\$ ${_pc_b_blue})-${_pc_b_yellow}-"
PS1="${PS1}${_pc_nocolour} "

export PS1

