#!/bin/bash
# shellcheck disable=SC1091  # <file> "not specified as input"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# shebang above is unnecessary, but helps vim identify the filetype
#

# User-settable:
bgColour="\e[48;5;022m"
fgColour="\e[38;5;226m"

echo "Prompt Title: urblock ('Upper Right Block of text')"
echo "Includes:     pwd, git, history number"
echo "For:          dark or light background"
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_git"

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi

    lineOne="${PWD/${HOME}/\~}"
    offsetOne=$(( COLUMNS - ${#lineOne} - 2 ))
    tput sc
    tput cup 0 ${offsetOne}
    echo -en "  "
    echo -en "${bgColour}"
    echo -en "${fgColour}"
    echo "${lineOne}"
    echo -en "\e[0m"
    tput rc

    lineTwo="$(_p_git)"
    offsetTwo=$(( COLUMNS - ${#lineTwo} - 2 ))
    tput sc
    tput cup 1 ${offsetTwo}
    echo -en "  "
    echo -en "${bgColour}"
    echo -en "${fgColour}"
    echo "${lineTwo}"
    echo -en "\e[0m"
    tput rc
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

_p_xtermtitle # generates the _p_TITLEBAR variable

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="\[${bgColour}${fgColour}\]\! ${_pc_nocolour}"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="\[${bgColour}${fgColour}\]\\\$${_pc_nocolour} "

