#!/bin/bash
#shellcheck disable=SC2016  # Expressions don't expand in single quotes ...
#
# Colours for prompts:
#    _pc_color          foreground colour
#    _pc_b_color bright foreground colour
#    _pc_bg_color       background colour
#
# NOTE: to combine a BG and FG, list the FG FIRST, then the BG colour.
#
# Colours without the prompt escape sequences:
#    _c_color           foreground colour
#    _c_b_color  bright foreground colour
#    _c_bg_color        background colour
#
# NOTE:
# Colours of the form "\[\e[38;5;015m\]" work fine in many contexts, and
# I've used them for years.  But if you attempt to pass them as parameters
# ... I haven't found any context or escape sequence to make that work.
# Instead, we use '\001[\033[38;5;015m\002'.

export _pc_nocolour='\001\033[0;0m\002'
export _pc_nocolor='\001\033[0;0m\002' # for our American friends
export _c_nocolour='\033[0m'
export _c_nocolor='\033[0m'

export _pc_bold='\001$(tput bold)\002'
export _pc_underline='\001$(tput smul)\002'
# italics display is very terminal-dependent: on some, it's reverse video.
export _pc_italics='\001$(tput sitm)\002'
export _pc_reverse='\001$(tput rev)\002'
export _pc_blink='\001$(tput blink)\002'

export _pc_black='\001\033[38;5;000m\002'
export _pc_b_black='\001\033[38;5;008m\002' # dark gray
export _pc_darkgray='\001\033[38;5;008m\002'
export _pc_bg_black='\001\033[48;5;000m\002'
export _c_black='\033[38;5;000m'
export _c_b_black='\033[38;5;008m'
export _c_darkgray='\033[38;5;008m'
export _c_bg_black='\033[48;5;000m'

export _pc_red='\001\033[38;5;001m\002'
export _pc_b_red='\001\033[38;5;009m\002'
export _pc_bg_red='\001\033[48;5;001m\002'
export _c_red='\033[38;5;001m'
export _c_b_red='\033[38;5;009m'
export _c_bg_red='\033[48;5;001m'

export _pc_green='\001\033[38;5;002m\002'
export _pc_b_green='\001\033[38;5;010m\002'
export _pc_bg_green='\001\033[48;5;002m\002'
export _c_green='\033[38;5;002m'
export _c_b_green='\033[38;5;010m'
export _c_bg_green='\033[48;5;002m'

export _pc_yellow='\001\033[38;5;003m\002'
export _pc_b_yellow='\001\033[38;5;011m\002'
export _pc_bg_yellow='\001\033[48;5;003m\002'
export _c_yellow='\033[38;5;003m'
export _c_b_yellow='\033[38;5;011m'
export _c_bg_yellow='\033[48;5;003m'

export _pc_blue='\001\033[38;5;004m\002'
export _pc_b_blue='\001\033[38;5;012m\002'
export _pc_bg_blue='\001\033[48;5;004m\002'
export _c_blue='\033[38;5;004m'
export _c_b_blue='\033[38;5;012m'
export _c_bg_blue='\033[48;5;004m'

export _pc_purple='\001\033[38;5;005m\002'
export _pc_b_purple='\001\033[38;5;013m\002'
export _pc_bg_purple='\001\033[48;5;005m\002'
export _c_purple='\033[38;5;005m'
export _c_b_purple='\033[38;5;013m'
export _c_bg_purple='\033[48;5;005m'

export _pc_cyan='\001\033[38;5;006m\002'
export _pc_b_cyan='\001\033[38;5;014m\002'
export _pc_bg_cyan='\001\033[48;5;006m\002'
export _c_cyan='\033[38;5;006m'
export _c_b_cyan='\033[38;5;014m'
export _c_bg_cyan='\033[48;5;006m'

export _pc_gray='\001\033[38;5;007m\002'
export _pc_b_gray='\001\033[38;5;015m\002' # almost white
export _pc_bg_gray='\001\033[48;5;007m\002'
export _c_gray='\033[38;5;007m'
export _c_b_gray='\033[38;5;015m'
export _c_bg_gray='\033[48;5;007m'

