#!/bin/bash
#
# Colours for prompts:
#    _pc_color          foreground colour
#    _pc_b_color   bold foreground colour
#    _pc_bg_color       background colour
#
# NOTE: to combine a BG and FG, list the FG FIRST, then the BG colour.
#
# Colours without the prompt escape sequences:
#    _c_color           foreground colour
#    _c_b_color    bold foreground colour
#    _c_bg_color        background colour
#
# NOTE:
# Colours of the form "\[\e[1;37m\]" work fine in many contexts, and I've
# used them for years.  But if you attempt to pass them as parameters ... I
# haven't found any context or escape sequence to make that work.  Instead,
# we use '\001[\e[1;37m\002'.

export _pc_nocolour='\001\033[0m\002'
export _pc_nocolor='\001\033[0m\002' # for our American friends
export _c_nocolour='\033[0m'
export _c_nocolor='\033[0m'

export _pc_black='\001\033[30m\002'
export _pc_b_black='\001\033[1;30m\002' # dark gray
export _pc_darkgray='\001\033[1;30m\002'
export _pc_bg_black='\001\033[40m\002'
export _c_black='\033[30m'
export _c_b_black='\033[1;30m'
export _c_darkgray='\033[1;30m'
export _c_bg_black='\033[40m'

export _pc_red='\001\033[31m\002'
export _pc_b_red='\001\033[1;31m\002'
export _pc_bg_red='\001\033[41m\002'
export _c_red='\033[31m'
export _c_b_red='\033[1;31m'
export _c_bg_red='\033[41m'

export _pc_green='\001\033[32m\002'
export _pc_b_green='\001\033[1;32m\002'
export _pc_bg_green='\001\033[42m\002'
export _c_green='\033[32m'
export _c_b_green='\033[1;32m'
export _c_bg_green='\033[42m'

export _pc_yellow='\001\033[33m\002'
export _pc_b_yellow='\001\033[1;33m\002'
export _pc_bg_yellow='\001\033[43m\002'
export _c_yellow='\033[33m'
export _c_b_yellow='\033[1;33m'
export _c_bg_yellow='\033[43m'

export _pc_blue='\001\033[34m\002'
#export _pc_b_blue='\001\033[1;34m\002'
export _pc_b_blue='\001\e[1;34m\002'
export _pc_bg_blue='\001\033[44m\002'
export _c_blue='\033[34m'
export _c_b_blue='\033[1;34m'
export _c_bg_blue='\033[44m'

export _pc_purple='\001\033[35m\002'
export _pc_b_purple='\001\033[1;35m\002'
export _pc_bg_purple='\001\033[45m\002'
export _c_purple='\033[35m'
export _c_b_purple='\033[1;35m'
export _c_bg_purple='\033[45m'

export _pc_cyan='\001\033[36m\002'
export _pc_b_cyan='\001\033[1;36m\002'
export _pc_bg_cyan='\001\033[46m\002'
export _c_cyan='\033[36m'
export _c_b_cyan='\033[1;36m'
export _c_bg_cyan='\033[46m'

export _pc_gray='\001\033[37m\002'
export _pc_b_gray='\001\033[1;37m\002' # almost white
export _pc_bg_gray='\001\033[47m\002'
export _c_gray='\033[37m'
export _c_b_gray='\033[1;37m'
export _c_bg_gray='\033[47m'

