#!/bin/bash
# shebang isn't necessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Based on the "purple" prompt

_p_colour_main="${1}"
_p_colour_highlight="${2}"
_p_colour_special="${3}" # in this prompt = git

echo "Prompt Title: blockload"
echo "Includes:     threads/load, PWD, git status (yellow), newline, battery, user@host"
echo "Requires:     git"

source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/machine/_p_threadload"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/directory/_p_tildepwd"

prompt_command () {
    _p_retval=$? # capture the return value before you change it w/prompt
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
    _p_xtermtitle # generates the _p_TITLEBAR variable
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="\$(_p_threadload)"
PS1+=" "
PS1+="${_p_colour_highlight}[${_pc_nocolour}"
PS1+="${_p_colour_main}"
PS1+="\$(if ! [ -w \"\${PWD}\" ]; then echo \"${_pc_bg_red}\"; fi)"
PS1+="\$(_p_tildepwd)"
PS1+="${_pc_nocolour}"
PS1+="${_p_colour_highlight}]${_pc_nocolour}"
PS1+=" "
PS1+="${_p_colour_special}"
PS1+="\$(_p_git)"
PS1+="${_pc_nocolour}"
PS1+="\n"                           # newline
PS1+="${_p_colour_highlight}[${_pc_nocolour}"
if [ "${_p_has_battery}" == "true" ]
then
    PS1+="${_p_colour_main}"
    PS1+="\$(_p_powerconnected)"
    PS1+="\$(_p_powerpercent)"
    PS1+="%${_pc_nocolour}"
    PS1+="${_p_colour_highlight}"
    PS1+="|"
fi
PS1+="${_p_colour_main}\u${_pc_nocolour}"
PS1+="${_p_colour_highlight}@${_pc_nocolour}"
PS1+="${_p_colour_main}\h${_pc_nocolour}"
PS1+="${_p_colour_highlight}]${_pc_nocolour}"
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}"
PS1+="${_pc_nocolour}"
PS1+="${_pc_b_gray}\\\$"
PS1+="${_pc_nocolour} "

export PS1

