#!/bin/bash
# shebang is unnecessary, but helps vim identify the filetype
#
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."
# shellcheck disable=SC1091  # disable "not following" included files
# shellcheck disable=SC1117  # "backslash is literal"
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# Named for its original colours of blue and yellow.

_p_colour_main="${1}"
_p_colour_highlight="${2}"
_p_colour_special="${3}" # in this prompt = git

echo "Prompt Title: tonka"
echo "Includes:     battery, user@host, PWD, git status, newline, time"
echo "Requires:     git"

# Get the components we need:
source "${PROMPTDIR}/_p_colours" # get colours into the environment
source "${PROMPTDIR}/directory/_p_xtermtitle"
source "${PROMPTDIR}/directory/_p_git"
source "${PROMPTDIR}/machine/_p_powerconnected"
source "${PROMPTDIR}/machine/_p_powerpercent"

if [ "${_p_uid0}" == "true" ]
then
    export _p_usercolour="${_pc_b_red}"
else
    export _p_usercolour="${_p_colour_main}"
fi

prompt_command () {
    _p_retval=$? # capture the return value before you change it
    _p_xtermtitle # generates the _p_TITLEBAR variable
    local tmp
    tmp=$(_p_git)
    if [ "${tmp}x" == "x" ]
    then
        _p_git_output=""
    else
        _p_git_output=" ${tmp}"
    fi
    if (( _p_retval == 0 ))
    then
        # disappear the return value if it's zero
        _p_retval=""
    fi
}

PROMPT_COMMAND=" prompt_command ; ${PROMPT_COMMAND} "

PS1=""
PS1+="${_p_TITLEBAR}"
PS1+="${_p_colour_main}-${_pc_nocolour}"
PS1+="${_p_colour_highlight}-(${_pc_nocolour}"
# User @ Hostname:
PS1+="${_p_usercolour}\u${_pc_nocolour}"
PS1+="${_p_colour_highlight}@${_pc_nocolour}"
PS1+="${_p_colour_main}\h${_pc_nocolour}"
PS1+="${_p_colour_highlight})-(${_pc_nocolour}"
PS1+="${_p_colour_main}\${PWD}${_pc_nocolour}"
PS1+="${_p_colour_special}\${_p_git_output}${_pc_nocolour}"
PS1+="${_p_colour_highlight})-"
PS1+="${_p_colour_main}-${_pc_nocolour}"
PS1+="\n" # ------------------------------------------
PS1+="${_p_colour_main}-${_pc_nocolour}"
PS1+="${_p_colour_highlight}-(${_pc_nocolour}"
PS1+="${_p_colour_main}\D{%H%M}${_pc_nocolour}"
PS1+="${_p_colour_highlight}:${_pc_nocolour}"
if [[ "${_p_has_battery}" == "true" ]]
then
    PS1+="${_p_colour_main}\$(_p_powerconnected)\$(_p_powerpercent)%${_pc_nocolour}"
    PS1+="${_p_colour_highlight}:${_pc_nocolour}"
fi
PS1+="${_pc_bg_gray}${_pc_b_red}\${_p_retval}${_pc_nocolour}"
PS1+="${_pc_b_gray}\\\$ "
PS1+="${_p_colour_highlight})-${_pc_nocolour}"
PS1+="${_p_colour_main}-${_pc_nocolour} "

export PS1

