#!/bin/bash
# shellcheck disable=SC1090  # disable "Can't follow non-constant source."

source "${PROMPTDIR}/directory/_p_git_branch_only"
source "${PROMPTDIR}/directory/_p_git_status_only"

_p_git () {
    if [ "$(_p_git_branch_only)x" != "x" ]
    then
        _p_git_branch_only
        _p_git_status_only
    fi
}

