#!/bin/bash
#
# Uses the long output of "ls" to print the size of the current directory
# in kb.

_p_lssize () {
    lskb=$(command ls -l | command grep "^total " | command awk '{print $2}')
    echo -n "${lskb}kb"
}

