#!/bin/bash
#
# Shows a count of visible (ie. not hidden) files in the current directory.
# Does NOT include directories.

_p_numvisfiles () {
    command ls -l | command grep -c "^-" | command tr -d " "
}

