#!/bin/bash
#
# Shows a count of the number of hidden/dot files in the current directory.
# Does NOT include directories.

_p_numhiddenfiles () {
    command ls -A -l -d .* 2> /dev/null | command grep -c "^-" | command tr -d " "
}

