#!/bin/bash
# Shows a count of the number of hidden/dot directories in the current
# directory.

function _p_numhiddendirs () {
    # This method counts "." and ".." as dirs, so subtract 2
    echo -n "$(( $(ls -l -d .* | grep '^d' | wc -l | tr -d ' ') - 2 ))"
}

