#!/bin/bash
#
# Shows a count of the number of hidden/dot files in the current directory.
# Does NOT include directories.

function _p_numhiddenfiles () {
    ls -A -l -d .* | grep "^-" | wc -l | tr -d " "
}

