#!/bin/bash
# Shows a count of the number of devices (includes hidden ones, although
# that's not exactly common) in the current directory.

_p_numalldevices () {
    command ls -A -l | command grep -c "^[bc]" | command tr -d " "
}

