#!/bin/bash # helps vim identify the filetype
#
# Shortens the PWD to the length provided by the first parameter.  If no
# value is provided, "20" is used.

function _p_shortpwd () {
    if [ "${1}x" == "x" ]
    then
        let pwd_len=20
    else
        let pwd_len=${1}
    fi
    newPWD=$(pwd)
    newPWD=${newPWD/#${HOME}/\~} # Replace home dir with ~
    if [ ${#newPWD} -gt ${pwd_len} ]
    then
        if [ "${newPWD:0:1}" = "~" ]
        then
            newPWD="~..${newPWD:$((${#newPWD}-${pwd_len}))}"
        else
            newPWD="...${newPWD:$((${#newPWD}-${pwd_len}))}"
        fi
    fi
    echo -n "${newPWD}"
}

