#!/bin/bash
# Prints the bogomips rating of your current processor.
#
# This assumes that the bogomips ratings for all processors/cores are the
# same.  And the value shouldn't change during a session, so don't escape
# it - just run it once.

_p_bogomips () {
    command grep bogo /proc/cpuinfo | command head -n 1 | command awk '{print $NF}' | command awk -F "." '{print $1}'
}

