#!/bin/bash
#
# Shows each (Linux) system-attached disc and percentage df use on that
# disc.  Shows "?" for Mac or other OSes.

_p_df_percent () {
    # shellcheck disable=SC2154  # "referenced but not assigned"
    if [ "${_p_os}" == "Linux" ]
    then
        # finds all local mount-points and shows their percent use in parens
        while read -r mountpoint
        do
            echo -n "($( command df --output=pcent "${mountpoint}" | command tail -n +2 | command tr -d " " ))"
        done < <(command lsblk --output MOUNTPOINT --noheadings | command grep -v '^$' | command grep -v '[SWAP]' )
    elif [ "${_p_os}" == "Darwin" ]
    then
        echo -n "?"
    else
        echo -n "?"
    fi
}

