#!/bin/bash
#
# Show one block for each mount point on the machine.  Same as
# _p_df_stoplight but with no colours.  Each block is a circle: empty if
# below the "okay" threshold, half filled if above it, and full if above
# the "warning" threshold.
#
# WARNING: doesn't handle Mac, only returns "?"

_p_df_sl () {
    # shellcheck disable=SC2154  # "referenced but not assigned"
    if [ "${_p_os}" == "Darwin" ]
    then
        # This doesn't work on Mac
        echo "?"
    fi

    okay=70     # percentage
    warning=90

    warning_char="●"
    mid_char="◐"
    okay_char="○"

    while read -r mountpoint
    do
        percent=$( command df --output=pcent "${mountpoint}" | command tail -n +2 | command tr -d '%' )
        if [ "${percent}" -gt "${warning}" ]
        then
            echo -n "${warning_char}"
        elif [ "${percent}" -gt "${okay}" ]
        then
            echo -n "${mid_char}"
        else
            echo -n "${okay_char}"
        fi
    done < <( command lsblk --output MOUNTPOINT --noheadings | command grep -v '^$' | command grep -v '[SWAP]' | command grep -v '^/snap/' ; command mount | command grep " cifs " | command awk '{ print $3 }' )
}

