#!/bin/bash
# Prints a single character colourized based on load.
#
# shellcheck disable=SC2154  # "referenced but not assigned"
#
# We do some math to figure this out.  $_p_numthreads is set in 'promnow'
# and provides the number of threads available on the current machine.  How
# much load is acceptable is determined by multiplying the current load by
# 100, dividing by the number of threads, and changing the character
# appearance at MEDIUMLOAD (default 50) and HIGHLOAD (default 100).  No
# character below MEDIUMLOAD, yellow character above MEDIUMLOAD but below
# HIGHLOAD, red character above HIGHLOAD.
#
# This has the same logic of _p_loadcaret: the only difference is that
# shows "^" on a coloured background, and this shows "▲" colourized.

MEDIUMLOAD=50
HIGHLOAD=100

_p_loadcaret2 () {
    load="$(command uptime | command awk '{print $(NF-2)}' | command tr -d ",")"
    percentload="$(command echo -e "scale=0 ; ${load}*100/${_p_numthreads}" | command bc)"
    if (( percentload > HIGHLOAD ))
    then
        _p_loadcaret_color="${_pc_b_red}"
    elif (( percentload > MEDIUMLOAD ))
    then
        _p_loadcaret_color="${_pc_b_yellow}"
    else
        _p_loadcaret_color=""
    fi

    if [ -n "${_p_loadcaret_color}" ]
    then
        echo -e "${_p_loadcaret_color}▲${_pc_nocolour}"
    fi
}

