#!/bin/bash
# Prints the current (1 minute) load.
#
# Removing the trailing comma isn't necessary on Mac, but is on Linux

_p_load () {
    # If you wanted:
    # - the  5 minute load: $(NF-1)
    # - the 15 minute load: $NF
    command uptime | command awk '{print $(NF-2)}' | command tr -d ","
}

