#!/bin/bash
# Prints the percentage battery power available: just the number, no
# trailing "%" sign.

# TODO:
# - Linux version would almost certainly barf on dual batteries

function _p_powerpercent () {
    if [ -e /sys ]
    then
        # On a Linux system:
        if [ -d /sys/class/power_supply/BAT?/ ] # Check there's a battery
        then
            cat /sys/class/power_supply/BAT?/capacity
        fi
    elif [ "$(command uname -a | command grep Darwin > /dev/null ; echo $?)" == "0" ]
    then # On a Mac:
        # This matches on Sierra, should also match on El Capitan:
        tmp=$(command pmset -g batt | command tail -1 | command sed 's/.*[[:space:]]\([1-9][0-9]*\)%;.*/\1/')
        echo -n "${tmp}"
    else
        # On an unknown system:
        echo -n "???"
    fi
}

