#!/bin/bash
# Gives a single character indicator of whether power is available.

function _p_powerconnected () {
    if [ -e /sys ]
    then
        # On a Linux system:
        if [ -d /sys/class/power_supply/BAT?/ ] # Check there's a battery
        then
            case $(cat /sys/class/power_supply/BAT?/status) in
                Full)        echo "" ;;
                Discharging) echo "v";;
                Charging)    echo "^";;
                *)           echo "?";;
            esac
        fi
    elif [ "$(command uname -a | command grep Darwin > /dev/null ; echo $?)" == "0" ]
    then # On a Mac:
        # This matches on Sierra and should work on El Capitan:
        tmp=$(command pmset -g batt | command tail -1 | command sed 's/.*[[:space:]]\([^[:space:]]*charg[^[:space:]]*\);.*/\1/')
        case ${tmp} in
            discharging) echo "v";;
            charging)    echo "^";;
            charged)     echo "" ;;
            *)           echo "?";;
        esac
    else
        # On an unknown system:
        echo -n "???"
    fi
}

