#!/bin/bash
# Prints the percentage battery power available: just the number, no
# trailing "%" sign.

# TODO:
# - Linux version would almost certainly barf on dual batteries

function _p_powerpercent () {
    if [ "${_p_os}" == "Linux" ]
    then
        # On a Linux system:
        if [ -d /sys/class/power_supply/BAT?/ ] # Check there's a battery
        then
            cat /sys/class/power_supply/BAT?/capacity
        fi
    elif [ "${_p_os}" == "Darwin" ]
    then # On a Mac:
        # This matches on Sierra, should also match on El Capitan:
        tmp=$(command pmset -g batt | command tail -1 | command sed 's/.*[[:space:]]\([1-9][0-9]*\)%;.*/\1/')
        re='^[0-9]+$'
        if [[ ${tmp} =~ ${re} ]]
        then
            echo -n "${tmp}"
        fi # if it's not numeric, the system doesn't have a battery?
    else
        # On an unknown system:
        echo -n "???"
    fi
}

