#!/bin/bash
#
# shows your tty number: on console "/dev/tty4" becomes "tty4" in the
# prompt, and in X "/dev/pts/4" becomes "4" in the prompt.

_p_shorttty () {
    command basename "$(command tty)"
}

