#!/bin/bash
# Prints the number of CPUs

_p_threadcount () {
    # shellcheck disable=SC2154  # "referenced but not assigned"
    if [ "${_p_os}" == "Linux" ]
    then
        numCPUs="$(grep -c 'siblings' /proc/cpuinfo)"
    elif [ "${_p_os}" == "Darwin" ]
    then
        # this method valid Monterey / 2022-02
        numCPUs="$(sysctl -n hw.ncpu)"
    else
        numCPUs="?"
    fi
    echo -n "${numCPUs}"
}

