#!/bin/bash
#
# Returns current uptime in the seconds (Mac and Linux).
#
# Intended for internal use - would usually be used to calculate the uptime
# in a more human-readable form (see _p_uptime).

function _p_upseconds () {
    if [ -e /proc/uptime ]
    then
        # http://askubuntu.com/questions/335592/how-to-display-time-elapsed-since-last-system-boot-using-uptime
        # /proc/uptime provides two numbers, the first is how long the
        # system has been up in seconds, the second is how much of that
        # time the machine has spent idle in seconds.
        let upSeconds="$(awk -F "." '{print $1}' /proc/uptime)"
    elif [ "$(uname -a | grep Darwin > /dev/null ; echo $?)" == "0" ]
    then
        # On a Mac.
        # "sysctl kern.boottime" shows the time of the last boot in seconds
        # since the millennia, so we need to work out the number of seconds
        # since then.
        let upSeconds=$(( $(date +%s) - $(sysctl kern.boottime | awk '{print $5}' | tr -d ",") ))
    fi
    echo -n "${upSeconds}"
}

