#!/bin/bash
#
# Returns current uptime in the form "5h3m", "7d22h", or "43d" for both
# Linux and Mac.

# an auxiliary function needed by this one that abstracts away the OS
# differences:
# shellcheck disable=1091  # Not following:
source "${PROMPTDIR}/machine/_p_upseconds"

_p_uptime () {
    seconds2uptime () {
        # Not currently used - and the linter complains:
        #secs=$((${1}%60))
        mins=$((${1}/60%60))
        hours=$((${1}/3600%24))
        days=$((${1}/86400))
        if [ "${days}" -gt "29" ]
        then
            echo -n "${days}d"
        elif [ "${days}" -ne "0" ]
        then
            echo -n "${days}d${hours}h"
        else
            echo -n "${hours}h${mins}m"
        fi
    }

    seconds2uptime "$(_p_upseconds)"
}

