#!/bin/bash
# shellcheck disable=SC1117
# From https://unix.stackexchange.com/questions/269077/tput-setaf-color-table-how-to-determine-color-codes
# which says this is about tput colours ... which it doesn't (directly)
# use.  This is BG colours only: is there a way to do FG colours?

color(){
    for c; do
        printf '\e[48;5;%dm %03d ' "${c}" "${c}"
    done
    printf '\e[0m \n'
}

IFS=$' \t\n'
echo "Base colours:"
color {0..15}
echo ""
echo "More than 16 colours (fine on Mac, Fedora, probably breaks on default Debian):"
for ((i=0;i<6;i++)); do
    color $(seq $((i*36+16)) $((i*36+51)))
done
echo ""
echo "Shades of gray (fine on Mac, Fedora, probably breaks on default Debian):"
color {232..255}

echo ""
echo -e "Example colour gradient: \033[48;5;005m \033[48;5;201m \033[48;5;207m \033[48;5;213m \033[48;5;218m \033[48;5;224m \033[48;5;229m \033[48;5;011m \033[0m (005,201,207,213,218,224,229,011)"

